import { SkillOption } from "../types";

export const AVAILABLE_SKILLS: SkillOption[] = [
  { id: "1password", name: "1Password", desc: "Set up and use 1Password CLI (op) for secrets management." },
  { id: "apple-notes", name: "Apple Notes", desc: "Manage Apple Notes on macOS (create, view, edit, search)." },
  { id: "apple-reminders", name: "Apple Reminders", desc: "Manage Apple Reminders on macOS (list, add, complete)." },
  { id: "bear-notes", name: "Bear Notes", desc: "Create, search, and manage Bear notes via grizzly CLI." },
  { id: "blogwatcher", name: "Blogwatcher", desc: "Monitor blogs and RSS/Atom feeds for updates." },
  { id: "blucli", name: "BluOS", desc: "BluOS CLI for discovery, playback, and volume control." },
  { id: "bluebubbles", name: "BlueBubbles", desc: "Send or manage iMessages via BlueBubbles.", requiresAuth: true, authPlaceholder: "Server URL & Password" },
  { id: "camsnap", name: "CamSnap", desc: "Capture frames or clips from RTSP/ONVIF cameras." },
  { id: "clawhub", name: "ClawHub", desc: "Search, install, update, and publish agent skills." },
  { id: "coding-agent", name: "Coding Agent", desc: "Run Codex, Claude Code, or OpenCode programmatic agents." },
  { id: "eightctl", name: "Eight Sleep", desc: "Control Eight Sleep pods (status, temperature, alarms)." },
  {
    id: "gemini",
    name: "Gemini CLI",
    desc: "Gemini CLI for one-shot Q&A, summaries, and generation.",
    requiresAuth: true,
    authMode: "oauth",
    oauthBaseProvider: "google",
    oauthMethod: "google-gemini-cli",
    oauthProviderId: "google-gemini-cli"
  },
  { id: "gifgrep", name: "GifGrep", desc: "Search GIF providers, download results, and extract frames." },
  { id: "github", name: "GitHub", desc: "Interact with GitHub using the gh CLI (issues, PRs, runs)." },
  { id: "gog", name: "Google Workspace", desc: "CLI for Gmail, Calendar, Drive, Docs, Sheets, and Contacts." },
  { id: "goplaces", name: "Google Places", desc: "Query Google Places API for search and details.", requiresAuth: true, authPlaceholder: "API Key" },
  { id: "healthcheck", name: "Healthcheck", desc: "Host security hardening and risk-tolerance configuration." },
  { id: "himalaya", name: "Himalaya (Email)", desc: "CLI to manage emails via IMAP/SMTP." },
  { id: "imsg", name: "iMessage", desc: "Native macOS iMessage/SMS CLI for chats and sending." },
  { id: "local-places", name: "Local Places", desc: "Search for places via Google Places API proxy." },
  { id: "mcporter", name: "MCPorter", desc: "List, configure, and call MCP servers/tools directly." },
  { id: "model-usage", name: "Model Usage", desc: "Summarize per-model usage/cost for Codex or Claude." },
  { id: "nano-banana-pro", name: "Nano Banana Pro", desc: "Generate or edit images via Gemini 3 Pro Image.", requiresAuth: true, authPlaceholder: "API Key" },
  { id: "nano-pdf", name: "Nano PDF", desc: "Edit PDFs with natural-language instructions." },
  { id: "notion", name: "Notion", desc: "Create and manage Notion pages and databases.", requiresAuth: true, authPlaceholder: "Integration Token" },
  { id: "obsidian", name: "Obsidian", desc: "Work with Obsidian vaults via obsidian-cli." },
  { id: "openai-image-gen", name: "OpenAI Images", desc: "Batch-generate images via OpenAI Images API.", requiresAuth: true, authPlaceholder: "API Key" },
  { id: "openai-whisper", name: "Whisper (Local)", desc: "Local speech-to-text with the Whisper CLI (no API key)." },
  { id: "openai-whisper-api", name: "Whisper API", desc: "Transcribe audio via OpenAI Audio API.", requiresAuth: true, authPlaceholder: "API Key" },
  { id: "openhue", name: "Philips Hue", desc: "Control Philips Hue lights/scenes via OpenHue CLI." },
  { id: "oracle", name: "Oracle", desc: "Best practices for using the oracle CLI." },
  { id: "ordercli", name: "OrderCLI", desc: "Foodora-only CLI for checking past/active orders." },
  { id: "peekaboo", name: "Peekaboo", desc: "Capture and automate macOS UI." },
  { id: "sag", name: "ElevenLabs TTS", desc: "ElevenLabs text-to-speech with mac-style say UX.", requiresAuth: true, authPlaceholder: "API Key" },
  { id: "session-logs", name: "Session Logs", desc: "Search and analyze your own session logs." },
  { id: "sherpa-onnx-tts", name: "Sherpa ONNX TTS", desc: "Local text-to-speech via sherpa-onnx (offline)." },
  { id: "skill-creator", name: "Skill Creator", desc: "Create or update AgentSkills." },
  { id: "slack", name: "Slack", desc: "Control Slack (messages, reactions, pins).", requiresAuth: true, authPlaceholder: "Bot Token" },
  { id: "songsee", name: "SongSee", desc: "Generate spectrograms and feature-panel visualizations." },
  { id: "sonoscli", name: "Sonos", desc: "Control Sonos speakers (status, playback, volume)." },
  { id: "spotify-player", name: "Spotify", desc: "Terminal Spotify playback/search via spogo." },
  { id: "summarize", name: "Summarize", desc: "Summarize text/transcripts from URLs and files." },
  { id: "things-mac", name: "Things 3", desc: "Manage Things 3 on macOS (add, list, search tasks)." },
  { id: "tmux", name: "Tmux", desc: "Remote-control tmux sessions for interactive CLIs." },
  { id: "trello", name: "Trello", desc: "Manage Trello boards, lists, and cards.", requiresAuth: true, authPlaceholder: "API Key & Token" },
  { id: "video-frames", name: "Video Frames", desc: "Extract frames or short clips from videos." },
  { id: "voice-call", name: "Voice Call", desc: "Start voice calls via the OpenClaw voice-call plugin." },
  { id: "wacli", name: "WhatsApp", desc: "Send WhatsApp messages via wacli CLI." },
  { id: "weather", name: "Weather", desc: "Get current weather and forecasts." },
];
